---
title: Database content
---
erDiagram
    User{
        id id PK
        timestamp created_at
        timestamp updated_at
        string name
        string email UK
        timestamp email_verified_at "Null"
        string password
        id lang FK "Null"
        string remember_token "Null"
        }
    Lang {
        string code PK
        string bgg_id
        string bgg_string
    }
    Game {
        string bgge_id PK "bgge stands for bgg extended: bgg -> number, others -> string "
        timestamp created_at
        timestamp updated_at
        timestamp last_sync_at
        string thumb_url "Null"
        string thumb_hash "Null"
        string thumb_blurhash "Null"
        string image_url "Null"
        string image_hash "Null"
        string image_blurhash "Null"
        int pub_year "Null"
        int min_players "Null"
        int max_players "Null"
        int min_age "Null"
        int box_time "Null"
        int min_time "Null"
        int max_time "Null"
        string name
        string version_of FK "Null"
        string description_hash
    }
    Question {
        id id PK
        string question_id
        string lang FK
        longText question
    }
    Answer {
        id id PK
        id writer_id FK
        string question_id
        string game_id FK
        int answer
    }
    Description {
        id id PK
        string game_id FK
        string lang FK
        string en_hash
        LongText description
    }
    Comment {
        id id PK
        timestamp created_at
        timestamp updated_at
        LongText content
        string lang FK
        string game_id FK
        id writer_id FK
        id editor_id FK "Null"
    }
    GameRole{
        id id PK
        timestamp created_at
        timestamp updated_at
        string role "Can be: Publisher, Designer, Artist"
        string bgge_id
        string bgge_game_id FK
        string name
    }
    User one or zero -- 0+ Comment  : edits
    User 1 -- 0+ Comment : writes
    Comment 1 -- 0+ Game : on
    Game 1 -- one or zero Game : "version of"
    Game 1+ -- 0+ Lang : "is available in"
    Game 1+ -- 1 Description: "described by"
    Game 0+ -- 1 GameRole: "worked on"
    Comment 1 -- 1+ Lang: "is in"
    User 1 -- 1+ Lang: speaks
    Description 1 -- 1+ Lang: "written in"
    Answer 1 -- 0+ Game: "evaluated on"
    Answer 1 -- 0+ Question: "answer of"
    Question 1 -- 0+ Lang: "written in"
    User 1+ -- 1+ Answer: "written by"

